name: Add new issue to org project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      contents: write  # required for org project access

    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/my-org/projects/2/views/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
