name: Add new issue to org project

on:
  issues:
    types: [opened]

permissions:
  issues: read
  contents: read
  # Project permissions are now under 'repository-projects' and 'organization-projects'
  repository-projects: write
  organization-projects: write

jobs:
  add-to-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/Vaquum/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
